
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"

#include "logger/logger.h"

// GListeners
GListener glistener;

// GHandles
GHandle ghContainerHome;
GHandle ghlb_home_title;
GHandle ghbtn_home_cycle;
GHandle ghbtn_home_charge;
GHandle ghbtn_home_settings;
GHandle ghlb_home_vbat;
GHandle ghlb_home_vfloat;

GHandle ghContainerSettings;
GHandle ghlb_settings_title;
GHandle ghbtn_settings_back;



// Fonts
font_t dejavu_sans_16;

static void createPageHome(void)
{

	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerHome
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerHome = gwinContainerCreate(0, &wi, 0);

	// Create label widget: ghlb_home_title
	wi.g.show = TRUE;
	wi.g.x = 20;
	wi.g.y = 0;
	wi.g.width = 300;
	wi.g.height = 20;
	wi.g.parent = ghContainerHome;
	wi.text = "Battery tester";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghlb_home_title = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlb_home_title, FALSE);
	gwinSetFont(ghlb_home_title, dejavu_sans_16);
	gwinRedraw(ghlb_home_title);

	// create button widget: ghbtn_home_cycle
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 60;
	wi.g.width = 300;
	wi.g.height = 50;
	wi.g.parent = ghContainerHome;
	wi.text = "Start cycle test";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghbtn_home_cycle = gwinButtonCreate(0, &wi);

	// create button widget: ghbtn_home_charge
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 120;
	wi.g.width = 300;
	wi.g.height = 50;
	wi.g.parent = ghContainerHome;
	wi.text = "Charge battery";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghbtn_home_charge = gwinButtonCreate(0, &wi);

	// create button widget: ghbtn_home_settings
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 180;
	wi.g.width = 300;
	wi.g.height = 50;
	wi.g.parent = ghContainerHome;
	wi.text = "Settings";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghbtn_home_settings = gwinButtonCreate(0, &wi);

	// Create label widget: ghlb_home_vbat
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 30;
	wi.g.width = 140;
	wi.g.height = 20;
	wi.g.parent = ghContainerHome;
	wi.text = "VBAT = 3800";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghlb_home_vbat = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlb_home_vbat, FALSE);

	// Create label widget: ghlb_home_vfloat
	wi.g.show = TRUE;
	wi.g.x = 170;
	wi.g.y = 30;
	wi.g.width = 140;
	wi.g.height = 20;
	wi.g.parent = ghContainerHome;
	wi.text = "Vfloat = 4200";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghlb_home_vfloat = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlb_home_vfloat, FALSE);
}

static void createPageSettings(void)
{
    GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerSettings
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerSettings = gwinContainerCreate(0, &wi, 0);

	// Create label widget: ghlb_home_title
	wi.g.show = TRUE;
	wi.g.x = 20;
	wi.g.y = 0;
	wi.g.width = 300;
	wi.g.height = 20;
	wi.g.parent = ghContainerSettings;
	wi.text = "Settings";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghlb_settings_title= gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlb_home_title, FALSE);
	gwinSetFont(ghlb_home_title, dejavu_sans_16);
	gwinRedraw(ghlb_home_title);

	// create button widget: ghbtn_home_cycle
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 60;
	wi.g.width = 300;
	wi.g.height = 50;
	wi.g.parent = ghContainerSettings;
	wi.text = "Back";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghbtn_settings_back = gwinButtonCreate(0, &wi);
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerHome);
	gwinHide(ghContainerSettings);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerHome);
		break;
    case 1:
		gwinShow(ghContainerSettings);
        break;
	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DejaVuSans16");

	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);
	gwinSetDefaultStyle(&white, FALSE);
	gwinSetDefaultColor(black_studio);
	gwinSetDefaultBgColor(white_studio);

	// Create all the display pages
	createPageHome();
    createPageSettings();

	// Select the default display page
	guiShowPage(0);

}

void guiEventLoop(void)
{
	GEvent* pe;

	geventListenerInit(&glistener);
	gwinAttachListener(&glistener);

	while (1) {
		// Get an event
		pe = geventEventWait(&glistener, portMAX_DELAY);
		switch (pe->type) {
        case GEVENT_GWIN_BUTTON:
            if (((GEventGWinButton*)pe)->gwin == ghbtn_home_cycle) {
                LOG("Cycle pressed\r\n");
            } else if (((GEventGWinButton*)pe)->gwin == ghbtn_home_charge) {
                LOG("Charge pressed\r\n");
            }else if (((GEventGWinButton*)pe)->gwin == ghbtn_home_settings) {
                LOG("Setting pressed\r\n");
                guiShowPage(1);
            }else if (((GEventGWinButton*)pe)->gwin == ghbtn_settings_back) {
                LOG("Setting back pressed\r\n");
                guiShowPage(0);
            }
		}

	}
}

void guiSetVBATValue(char *str) {

    gwinSetText(ghlb_home_vbat, str, FALSE);
}

