/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"

// GListeners
GListener glistener;

// GHandles
GHandle ghContainerHome;
GHandle ghlb_title;
GHandle ghbtn_cycle;
GHandle ghbtn_charge;
GHandle ghbtn_settings;
GHandle ghlb_vbat;
GHandle ghlb_vfloat;

// Fonts
font_t dejavu_sans_16;

static void createPageHome(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerHome
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerHome = gwinContainerCreate(0, &wi, 0);

	// Create label widget: ghlb_title
	wi.g.show = TRUE;
	wi.g.x = 20;
	wi.g.y = 0;
	wi.g.width = 300;
	wi.g.height = 20;
	wi.g.parent = ghContainerHome;
	wi.text = "Battery tester";
	wi.customDraw = gwinLabelDrawJustifiedCenter;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghlb_title = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlb_title, FALSE);
	gwinSetFont(ghlb_title, dejavu_sans_16);
	gwinRedraw(ghlb_title);

	// create button widget: ghbtn_cycle
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 60;
	wi.g.width = 300;
	wi.g.height = 50;
	wi.g.parent = ghContainerHome;
	wi.text = "Start cycle test";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghbtn_cycle = gwinButtonCreate(0, &wi);

	// create button widget: ghbtn_charge
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 120;
	wi.g.width = 300;
	wi.g.height = 50;
	wi.g.parent = ghContainerHome;
	wi.text = "Charge battery";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghbtn_charge = gwinButtonCreate(0, &wi);

	// create button widget: ghbtn_settings
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 180;
	wi.g.width = 300;
	wi.g.height = 50;
	wi.g.parent = ghContainerHome;
	wi.text = "Settings";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghbtn_settings = gwinButtonCreate(0, &wi);

	// Create label widget: ghlb_vbat
	wi.g.show = TRUE;
	wi.g.x = 10;
	wi.g.y = 30;
	wi.g.width = 140;
	wi.g.height = 20;
	wi.g.parent = ghContainerHome;
	wi.text = "VBAT = 3800";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghlb_vbat = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlb_vbat, FALSE);

	// Create label widget: ghlb_vfloat
	wi.g.show = TRUE;
	wi.g.x = 170;
	wi.g.y = 30;
	wi.g.width = 140;
	wi.g.height = 20;
	wi.g.parent = ghContainerHome;
	wi.text = "Vfloat = 4200";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghlb_vfloat = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(ghlb_vfloat, FALSE);
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerHome);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerHome);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DejaVuSans16");

	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);
	gwinSetDefaultStyle(&white, FALSE);
	gwinSetDefaultColor(black_studio);
	gwinSetDefaultBgColor(white_studio);
    gdispSetOrientation(GDISP_ROTATE_LANDSCAPE);

	// Create all the display pages
	createPageHome();

	// Select the default display page
	guiShowPage(0);

}

void guiEventLoop(void)
{
	GEvent* pe;

	while (1) {
		// Get an event
		pe = geventEventWait(&glistener, 0);
		switch (pe->type) {
		}

	}
}

