/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// GListeners
extern GListener glistener;

// GHandles
extern GHandle ghContainerHome;
extern GHandle ghlb_title;
extern GHandle ghbtn_cycle;
extern GHandle ghbtn_charge;
extern GHandle ghbtn_settings;
extern GHandle ghlb_vbat;
extern GHandle ghlb_vfloat;

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);
void guiSetVBATValue(char *str);
#endif /* _GUI_H_ */

