/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Courier New16.c                                       *
* Font:        Courier New                                           *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
*                                                                    *
**********************************************************************
*/

#include "font_def.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCourierNew16;

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0020[ 16] = { /* code 0020 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0021[ 16] = { /* code 0021 */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ___XX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0022[ 16] = { /* code 0022 */
  ________,
  ________,
  ________,
  ________,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0023[ 16] = { /* code 0023 */
  ________,
  ________,
  ________,
  ________,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_,
  _XX_XX__,
  XXXXXXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0024[ 16] = { /* code 0024 */
  ________,
  ________,
  ________,
  ___X____,
  __XXXXX_,
  _XX___X_,
  _XX_____,
  _XXXXX__,
  ___XXXX_,
  _X___XX_,
  _X___XX_,
  _XXXXX__,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0025[ 16] = { /* code 0025 */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  _X__X___,
  _X__X___,
  __XX_XX_,
  _XX_XX__,
  ___X__X_,
  ___X__X_,
  ____XX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0026[ 16] = { /* code 0026 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXX_XX_,
  XX_XXX__,
  XX__XX__,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0027[ 16] = { /* code 0027 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0028[ 16] = { /* code 0028 */
  ________,
  ________,
  ________,
  ________,
  ____X___,
  ___XX___,
  ___X____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ___X____,
  ___XX___,
  ____X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0029[ 16] = { /* code 0029 */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  __XX____,
  ___X____,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___X____,
  __XX____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_002A[ 16] = { /* code 002A */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  _XXXXXX_,
  __XXXX__,
  __XXXX__,
  __X__X__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_002B[ 16] = { /* code 002B */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_002C[ 16] = { /* code 002C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ____XX__,
  ____X___,
  ___XX___,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_002D[ 16] = { /* code 002D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_002E[ 16] = { /* code 002E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_002F[ 16] = { /* code 002F */
  ________,
  ________,
  ________,
  _____XX_,
  _____XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0030[ 16] = { /* code 0030 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0031[ 16] = { /* code 0031 */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0032[ 16] = { /* code 0032 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0033[ 16] = { /* code 0033 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  _____XX_,
  ___XXX__,
  _____XX_,
  _____XX_,
  _X___XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0034[ 16] = { /* code 0034 */
  ________,
  ________,
  ________,
  ________,
  ____XX__,
  ___XXX__,
  ___XXX__,
  __X_XX__,
  _X__XX__,
  _XXXXXX_,
  ____XX__,
  __XXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0035[ 16] = { /* code 0035 */
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  __XX____,
  __XXXX__,
  __X__XX_,
  _____XX_,
  _____XX_,
  _X___XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0036[ 16] = { /* code 0036 */
  ________,
  ________,
  ________,
  ________,
  ___XXXX_,
  __XX____,
  _XX_____,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0037[ 16] = { /* code 0037 */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___XX_,
  _____XX_,
  ____XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0038[ 16] = { /* code 0038 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0039[ 16] = { /* code 0039 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXXX_,
  _____XX_,
  ____XX__,
  _XXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_003A[ 16] = { /* code 003A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_003B[ 16] = { /* code 003B */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ____XX__,
  ____XX__,
  ________,
  ________,
  ____XX__,
  ___XX___,
  ___X____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_003C[ 16] = { /* code 003C */
  ________,
  ________,
  ________,
  ________,
  ________,
  _____XX_,
  ____X___,
  __XX____,
  XX______,
  __XX____,
  ____X___,
  _____XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_003D[ 16] = { /* code 003D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_003E[ 16] = { /* code 003E */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  ___X____,
  ____XX__,
  ______XX,
  ____XX__,
  ___X____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_003F[ 16] = { /* code 003F */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  ____XX__,
  ___XXX__,
  __XXX___,
  __XX____,
  ________,
  __XX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0040[ 16] = { /* code 0040 */
  ________,
  ________,
  ________,
  ________,
  ___XXX__,
  __X___X_,
  _X__XXX_,
  _X_X__X_,
  _X_X__X_,
  _X__XXX_,
  _X______,
  __X___X_,
  ___XXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0041[ 16] = { /* code 0041 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_,
  XX___XX_,
  XXX_XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0042[ 16] = { /* code 0042 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XXXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0043[ 16] = { /* code 0043 */
  ________,
  ________,
  ________,
  ________,
  ___XXXX_,
  __XX__X_,
  _XX___X_,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX__X_,
  ___XXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0044[ 16] = { /* code 0044 */
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  _XX_XX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX_XX__,
  XXXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0045[ 16] = { /* code 0045 */
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _XX___X_,
  _XX_X_X_,
  _XXXX___,
  _XX_X___,
  _XX___X_,
  _XX___X_,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0046[ 16] = { /* code 0046 */
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _XX___X_,
  _XX_X_X_,
  _XXXX___,
  _XX_X___,
  _XX_____,
  _XX_____,
  XXXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0047[ 16] = { /* code 0047 */
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX___X_,
  _XX___X_,
  _XX_____,
  _XX_XXXX,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0048[ 16] = { /* code 0048 */
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _XX__XX_,
  _XX__XX_,
  _XXXXXX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XXX__XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0049[ 16] = { /* code 0049 */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_004A[ 16] = { /* code 004A */
  ________,
  ________,
  ________,
  ________,
  _XXXXXXX,
  ____XX__,
  ____XX__,
  ____XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XXXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_004B[ 16] = { /* code 004B */
  ________,
  ________,
  ________,
  ________,
  XXXX_XXX,
  _XX__XX_,
  _XX_XX__,
  _XXXX___,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  XXXX__XX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_004C[ 16] = { /* code 004C */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX___X_,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_004D[ 16] = { /* code 004D */
  ________,
  ________,
  ________,
  ________,
  XX___XXX,
  XXX_XXX_,
  XXX_XXX_,
  XXX_XXX_,
  XX_X_XX_,
  XX_X_XX_,
  XX___XX_,
  XXX_XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_004E[ 16] = { /* code 004E */
  ________,
  ________,
  ________,
  ________,
  XXX_XXXX,
  _XX__XX_,
  _XXX_XX_,
  _XXX_XX_,
  _XX_XXX_,
  _XX_XXX_,
  _XX__XX_,
  XXXX_XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_004F[ 16] = { /* code 004F */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0050[ 16] = { /* code 0050 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX_____,
  _XX_____,
  XXXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0051[ 16] = { /* code 0051 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ___XX_X_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0052[ 16] = { /* code 0052 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX_XX__,
  _XX__XX_,
  XXXX__XX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0053[ 16] = { /* code 0053 */
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX___X_,
  _XX_____,
  __XXX___,
  ___XXX__,
  _____XX_,
  _X___XX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0054[ 16] = { /* code 0054 */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X_XX_X_,
  _X_XX_X_,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0055[ 16] = { /* code 0055 */
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0056[ 16] = { /* code 0056 */
  ________,
  ________,
  ________,
  ________,
  XXX_XXXX,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0057[ 16] = { /* code 0057 */
  ________,
  ________,
  ________,
  ________,
  XXX_XXXX,
  XX___XX_,
  XX_X_XX_,
  XXXXXXX_,
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0058[ 16] = { /* code 0058 */
  ________,
  ________,
  ________,
  ________,
  XXX_XXXX,
  _XX__XX_,
  __XXXX__,
  ___XX___,
  ___XX___,
  __XXXX__,
  _XX__XX_,
  XXXX_XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0059[ 16] = { /* code 0059 */
  ________,
  ________,
  ________,
  ________,
  XXX_XXXX,
  _XX__XX_,
  __X__X__,
  __XXXX__,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_005A[ 16] = { /* code 005A */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___XX_,
  _X__XX__,
  ___XX___,
  ___XX___,
  __XX__X_,
  _XX___X_,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_005B[ 16] = { /* code 005B */
  ________,
  ________,
  ________,
  ________,
  ___XXXX_,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_005C[ 16] = { /* code 005C */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ____XX__,
  ____XX__,
  _____XX_,
  _____XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_005D[ 16] = { /* code 005D */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_005E[ 16] = { /* code 005E */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  __X_X___,
  _X___X__,
  _X___X__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_005F[ 16] = { /* code 005F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0060[ 16] = { /* code 0060 */
  ________,
  ________,
  ________,
  __X_____,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0061[ 16] = { /* code 0061 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _____XX_,
  __XXXXX_,
  _XX__XX_,
  _XX__XX_,
  __XXXXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0062[ 16] = { /* code 0062 */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  _XX_XX__,
  _XXX_XX_,
  _XX__XX_,
  _XX__XX_,
  _XXX_XX_,
  XXX_XX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0063[ 16] = { /* code 0063 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX___X_,
  _XX___X_,
  _XX_____,
  _XX___X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0064[ 16] = { /* code 0064 */
  ________,
  ________,
  ________,
  ________,
  ____XXX_,
  _____XX_,
  __XX_XX_,
  _XX_XXX_,
  _XX__XX_,
  _XX__XX_,
  _XX_XXX_,
  __XX_XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0065[ 16] = { /* code 0065 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XXXXXX_,
  _XX_____,
  _XX___X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0066[ 16] = { /* code 0066 */
  ________,
  ________,
  ________,
  ________,
  ___XXXX_,
  __XX____,
  XXXXXXX_,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0067[ 16] = { /* code 0067 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX_XXX,
  _XX_XXX_,
  _XX__XX_,
  _XX__XX_,
  _XX_XXX_,
  __XX_XX_,
  _____XX_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0068[ 16] = { /* code 0068 */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XXX__XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0069[ 16] = { /* code 0069 */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ________,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_006A[ 16] = { /* code 006A */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ________,
  XXXXXX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_006B[ 16] = { /* code 006B */
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  _XX_XXX_,
  _XX_XX__,
  _XXXX___,
  _XXXXX__,
  _XX__XX_,
  XXX__XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_006C[ 16] = { /* code 006C */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_006D[ 16] = { /* code 006D */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_006E[ 16] = { /* code 006E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XXX__XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_006F[ 16] = { /* code 006F */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0070[ 16] = { /* code 0070 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XX__,
  _XXX_XX_,
  _XX__XX_,
  _XX__XX_,
  _XXX_XX_,
  _XX_XX__,
  _XX_____,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0071[ 16] = { /* code 0071 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX_XXX,
  _XX_XXX_,
  _XX__XX_,
  _XX__XX_,
  _XX_XXX_,
  __XX_XX_,
  _____XX_,
  ___XXXXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0072[ 16] = { /* code 0072 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX_XX_,
  __XXX_X_,
  __XX____,
  __XX____,
  __XX____,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0073[ 16] = { /* code 0073 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX__XX_,
  _XXXX___,
  ___XXXX_,
  _XX__XX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0074[ 16] = { /* code 0074 */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  _XXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX__X_,
  ___XXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0075[ 16] = { /* code 0075 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0076[ 16] = { /* code 0076 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  __X_X___,
  __XXX___,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0077[ 16] = { /* code 0077 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXXX,
  XX_X_XX_,
  XX_X_XX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0078[ 16] = { /* code 0078 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _XX__XX_,
  __XXXX__,
  __XXXX__,
  _XX__XX_,
  XXX__XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_0079[ 16] = { /* code 0079 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX_XXX,
  _XX__XX_,
  _XX_XX__,
  __X_XX__,
  __XXX___,
  ___XX___,
  __XX____,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_007A[ 16] = { /* code 007A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X__XX__,
  ___XX___,
  __XX____,
  _XX___X_,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_007B[ 16] = { /* code 007B */
  ________,
  ________,
  ________,
  ________,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ____XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_007C[ 16] = { /* code 007C */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_007D[ 16] = { /* code 007D */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_007E[ 16] = { /* code 007E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _X_X_X__,
  ____X___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_007F[ 16] = { /* code 007F */
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00A0[ 16] = { /* code 00A0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00A1[ 16] = { /* code 00A1 */
  ________,
  __X__X__,
  ___XX___,
  ________,
  XXXX_XXX,
  _XX__XX_,
  __X__X__,
  __XXXX__,
  ___XX___,
  ___XX___,
  X_XX____,
  XXX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00A2[ 16] = { /* code 00A2 */
  ________,
  ________,
  ________,
  __X__X__,
  ___XX___,
  ________,
  XXXX_XXX,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  __XXXX__,
  ___XX___,
  _X_XX___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00A3[ 16] = { /* code 00A3 */
  ________,
  ________,
  ________,
  ________,
  _XXXXXXX,
  ____XX__,
  ____XX__,
  ____XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XXXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00A4[ 16] = { /* code 00A4 */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX____XX,
  XXXXXXXX,
  _XX__XX_,
  _XX__XX_,
  XXXXXXXX,
  XX____XX,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00A5[ 16] = { /* code 00A5 */
  ________,
  ________,
  ________,
  ______X_,
  _XXXXXX_,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  _XXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00A6[ 16] = { /* code 00A6 */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00A7[ 16] = { /* code 00A7 */
  ________,
  ________,
  ________,
  ________,
  ___XXX__,
  __X__X__,
  _XX_____,
  _X_XX___,
  __X__X__,
  ___XX_X_,
  _____XX_,
  __X__X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00A8[ 16] = { /* code 00A8 */
  ________,
  ________,
  __X__X__,
  ________,
  XXXXXXX_,
  _XX___X_,
  _XX_X_X_,
  _XXXX___,
  _XX_X___,
  _XX___X_,
  _XX___X_,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00A9[ 16] = { /* code 00A9 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  X__XXX_X,
  X_X__X_X,
  X_X____X,
  X__XXX_X,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00AA[ 16] = { /* code 00AA */
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX__XX_,
  _XX_____,
  _XXXX___,
  _XX_____,
  _XX_____,
  _XX___X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00AB[ 16] = { /* code 00AB */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X___X,
  __X___X_,
  _X___X__,
  _X___X__,
  __X___X_,
  ___X___X,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00AC[ 16] = { /* code 00AC */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ______X_,
  ______X_,
  ______X_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00AD[ 16] = { /* code 00AD */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00AE[ 16] = { /* code 00AE */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  X_XXXX_X,
  X__X_X_X,
  X__XX__X,
  X_XX_X_X,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00AF[ 16] = { /* code 00AF */
  ________,
  ________,
  __X__X__,
  ________,
  _XXXXXX_,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00B0[ 16] = { /* code 00B0 */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  __X__X__,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00B1[ 16] = { /* code 00B1 */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00B2[ 16] = { /* code 00B2 */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00B3[ 16] = { /* code 00B3 */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ________,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00B4[ 16] = { /* code 00B4 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ______X_,
  _XXXXXX_,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  _XXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00B5[ 16] = { /* code 00B5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXXXX,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00B6[ 16] = { /* code 00B6 */
  ________,
  ________,
  ________,
  ________,
  __XXXXXX,
  _XX_X_X_,
  _XX_X_X_,
  _XX_X_X_,
  __XXX_X_,
  ____X_X_,
  ____X_X_,
  ____X_X_,
  __XXXXXX,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00B7[ 16] = { /* code 00B7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00B8[ 16] = { /* code 00B8 */
  ________,
  ________,
  ________,
  ________,
  __X__X__,
  ________,
  __XXXX__,
  _XX__XX_,
  _XXXXXX_,
  _XX_____,
  _XX___X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00B9[ 16] = { /* code 00B9 */
  ________,
  ________,
  ________,
  ________,
  X_XXX___,
  XX_X_XXX,
  XX_X_X_X,
  XX_X_XXX,
  X_XX____,
  X_XX_XXX,
  X_XX____,
  XX_X____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00BA[ 16] = { /* code 00BA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX__XX_,
  _XXXX___,
  _XX_____,
  _XX___X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00BB[ 16] = { /* code 00BB */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  _X___X__,
  __X___X_,
  __X___X_,
  _X___X__,
  X___X___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00BC[ 16] = { /* code 00BC */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ________,
  XXXXXX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00BD[ 16] = { /* code 00BD */
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX___X_,
  _XX_____,
  __XXX___,
  ___XXX__,
  _____XX_,
  _X___XX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00BE[ 16] = { /* code 00BE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX__XX_,
  _XXXX___,
  ___XXXX_,
  _XX__XX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00BF[ 16] = { /* code 00BF */
  ________,
  ________,
  ________,
  ________,
  __X__X__,
  ________,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00C0[ 16] = { /* code 00C0 */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_,
  XX___XX_,
  XXX_XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00C1[ 16] = { /* code 00C1 */
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _XX___X_,
  _XX_____,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XXXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00C2[ 16] = { /* code 00C2 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XXXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00C3[ 16] = { /* code 00C3 */
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _XX__XX_,
  _XX__XX_,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00C4[ 16] = { /* code 00C4 */
  ________,
  ________,
  ________,
  ________,
  _XXXXXXX,
  __XX_XX_,
  __XX_XX_,
  __XX_XX_,
  __XX_XX_,
  __XX_XX_,
  _XX__XX_,
  XXXXXXXX,
  X______X,
  X______X,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00C5[ 16] = { /* code 00C5 */
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _XX___X_,
  _XX_X_X_,
  _XXXX___,
  _XX_X___,
  _XX___X_,
  _XX___X_,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00C6[ 16] = { /* code 00C6 */
  ________,
  ________,
  ________,
  ________,
  XX_XX_XX,
  _X_XX_X_,
  __XXXX__,
  ___XX___,
  __XXXX__,
  _X_XX_X_,
  _X_XX_X_,
  XX_XX_XX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00C7[ 16] = { /* code 00C7 */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___XX_,
  _X___XX_,
  ___XXX__,
  _____XX_,
  _____XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00C8[ 16] = { /* code 00C8 */
  ________,
  ________,
  ________,
  ________,
  XXXX_XXX,
  _XX__XX_,
  _XX_XXX_,
  _XX_XXX_,
  _XXX_XX_,
  _XXX_XX_,
  _XX__XX_,
  XXX_XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00C9[ 16] = { /* code 00C9 */
  ________,
  __X__X__,
  ___XX___,
  ________,
  XXXX_XXX,
  _XX__XX_,
  _XX_XXX_,
  _XX_XXX_,
  _XXX_XX_,
  _XXX_XX_,
  _XX__XX_,
  XXX_XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00CA[ 16] = { /* code 00CA */
  ________,
  ________,
  ________,
  ________,
  XXX__XX_,
  _XX_XXX_,
  _XXXX___,
  _XXXX___,
  _XX_XX__,
  _XX__XX_,
  _XX__XX_,
  XXXX__XX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00CB[ 16] = { /* code 00CB */
  ________,
  ________,
  ________,
  ________,
  _XXXXXXX,
  __XX_XX_,
  __XX_XX_,
  __XX_XX_,
  __XX_XX_,
  __XX_XX_,
  X_XX_XX_,
  XXX__XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00CC[ 16] = { /* code 00CC */
  ________,
  ________,
  ________,
  ________,
  XX___XXX,
  XXX_XXX_,
  XXX_XXX_,
  XXX_XXX_,
  XX_X_XX_,
  XX_X_XX_,
  XX___XX_,
  XXX_XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00CD[ 16] = { /* code 00CD */
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _XX__XX_,
  _XX__XX_,
  _XXXXXX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XXX__XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00CE[ 16] = { /* code 00CE */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00CF[ 16] = { /* code 00CF */
  ________,
  ________,
  ________,
  ________,
  XXXXXXXX,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XXXX_XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00D0[ 16] = { /* code 00D0 */
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX_____,
  _XX_____,
  XXXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00D1[ 16] = { /* code 00D1 */
  ________,
  ________,
  ________,
  ________,
  ___XXXX_,
  __XX__X_,
  _XX___X_,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX__X_,
  ___XXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00D2[ 16] = { /* code 00D2 */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X_XX_X_,
  _X_XX_X_,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00D3[ 16] = { /* code 00D3 */
  ________,
  ________,
  ________,
  ________,
  XXXX_XXX,
  _XX__XX_,
  __X__X__,
  __XXXX__,
  ___XX___,
  ___XX___,
  X_XX____,
  XXX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00D4[ 16] = { /* code 00D4 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  ___XX___,
  _XXXXXX_,
  XX_XX_XX,
  XX_XX_XX,
  _XXXXXX_,
  ___XX___,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00D5[ 16] = { /* code 00D5 */
  ________,
  ________,
  ________,
  ________,
  XXX_XXXX,
  _XX__XX_,
  __XXXX__,
  ___XX___,
  ___XX___,
  __XXXX__,
  _XX__XX_,
  XXXX_XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00D6[ 16] = { /* code 00D6 */
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XXXXXXXX,
  _______X,
  _______X,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00D7[ 16] = { /* code 00D7 */
  ________,
  ________,
  ________,
  ________,
  XXXX_XXX,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXXX_,
  _____XX_,
  ____XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00D8[ 16] = { /* code 00D8 */
  ________,
  ________,
  ________,
  ________,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XXXXXXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00D9[ 16] = { /* code 00D9 */
  ________,
  ________,
  ________,
  ________,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XXXXXXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00DA[ 16] = { /* code 00DA */
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  X_XX____,
  __XX____,
  __XXXXX_,
  __XX__XX,
  __XX__XX,
  __XX__XX,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00DB[ 16] = { /* code 00DB */
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XXXX__XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XXXX_XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00DC[ 16] = { /* code 00DC */
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _XX_____,
  _XX_____,
  _XXXXXX_,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00DD[ 16] = { /* code 00DD */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX__XX_,
  _____XX_,
  ___XXXX_,
  _____XX_,
  _____XX_,
  _X___XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00DE[ 16] = { /* code 00DE */
  ________,
  ________,
  ________,
  ________,
  XX__XXX_,
  XX_XX_XX,
  XX_XX_XX,
  XXXXX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX__XXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00DF[ 16] = { /* code 00DF */
  ________,
  ________,
  ________,
  ________,
  __XXXXXX,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXXX_,
  __XX_XX_,
  _XX__XX_,
  XX__XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00E0[ 16] = { /* code 00E0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _____XX_,
  __XXXXX_,
  _XX__XX_,
  _XX__XX_,
  __XXXXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00E1[ 16] = { /* code 00E1 */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX_____,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00E2[ 16] = { /* code 00E2 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  _XX_XX__,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  XXXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00E3[ 16] = { /* code 00E3 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _XX___X_,
  _XX___X_,
  _XX_____,
  _XX_____,
  XXXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00E4[ 16] = { /* code 00E4 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  __X_XX__,
  __X_XX__,
  __X_XX__,
  __X_XX__,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00E5[ 16] = { /* code 00E5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XXXXXX_,
  _XX_____,
  _XX___X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00E6[ 16] = { /* code 00E6 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX_XX,
  _X_XX_X_,
  __XXXX__,
  _X_XX_X_,
  _X_XX_X_,
  XX_XX_XX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00E7[ 16] = { /* code 00E7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX__XX_,
  _XX_XX__,
  _____XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00E8[ 16] = { /* code 00E8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX_XXX,
  _XX_XXX_,
  _XX_XXX_,
  _XXX_XX_,
  _XXX_XX_,
  XXX_XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00E9[ 16] = { /* code 00E9 */
  ________,
  ________,
  ________,
  __X__X__,
  ___XX___,
  ________,
  XXXX_XXX,
  _XX_XXX_,
  _XX_XXX_,
  _XXX_XX_,
  _XXX_XX_,
  XXX_XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00EA[ 16] = { /* code 00EA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX_XXX,
  _XX_XX_X,
  _XXXX___,
  _XX_XX__,
  _XX__XX_,
  XXXX_XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00EB[ 16] = { /* code 00EB */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXXX,
  __XX_XX_,
  __XX_XX_,
  __XX_XX_,
  X_XX_XX_,
  XXX_XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00EC[ 16] = { /* code 00EC */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX___XX,
  _XXX_XX_,
  _XXX_XX_,
  _XX_X_X_,
  _XX___X_,
  XXXX_XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00ED[ 16] = { /* code 00ED */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXXX,
  _XX__XX_,
  _XXXXXX_,
  _XX__XX_,
  _XX__XX_,
  XXXX_XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00EE[ 16] = { /* code 00EE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00EF[ 16] = { /* code 00EF */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXXX,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XXXX_XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00F0[ 16] = { /* code 00F0 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XX__,
  _XXX_XX_,
  _XX__XX_,
  _XX__XX_,
  _XXX_XX_,
  _XX_XX__,
  _XX_____,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00F1[ 16] = { /* code 00F1 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX___X_,
  _XX___X_,
  _XX_____,
  _XX___X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00F2[ 16] = { /* code 00F2 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X_XX_X_,
  _X_XX_X_,
  ___XX___,
  ___XX___,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00F3[ 16] = { /* code 00F3 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX_XXX,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  __XXXX__,
  ___XX___,
  _X_XX___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00F4[ 16] = { /* code 00F4 */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  ___XX___,
  _XXXXXX_,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  _XXXXXX_,
  ___XX___,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00F5[ 16] = { /* code 00F5 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _XX__XX_,
  __XXXX__,
  __XXXX__,
  _XX__XX_,
  XXX__XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00F6[ 16] = { /* code 00F6 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XXXXXXXX,
  _______X,
  _______X,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00F7[ 16] = { /* code 00F7 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  __XXXX__,
  ____XX__,
  ___XXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00F8[ 16] = { /* code 00F8 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XXXXXXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00F9[ 16] = { /* code 00F9 */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XXXXXXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00FA[ 16] = { /* code 00FA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  X_XX____,
  X_XXXXX_,
  __XX__XX,
  __XX__XX,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00FB[ 16] = { /* code 00FB */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  XX____XX,
  XXXX__XX,
  XX__X_XX,
  XX__X_XX,
  XXXX_XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00FC[ 16] = { /* code 00FC */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _XX_____,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  XXXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00FD[ 16] = { /* code 00FD */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX__XX_,
  ___XXXX_,
  _____XX_,
  _X___XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00FE[ 16] = { /* code 00FE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XX_,
  _XX_XX_X,
  _XXXXX_X,
  _XX_XX_X,
  _XX_XX_X,
  XXX__XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontCourierNew16_00FF[ 16] = { /* code 00FF */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXXX,
  _XX__XX_,
  _XX__XX_,
  __XXXXX_,
  __XX_XX_,
  _XX_XXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontCourierNew16_CharInfo[192] = {
   {   8,   8,  1, acGUI_FontCourierNew16_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0021 } /* code 0021 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0022 } /* code 0022 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0023 } /* code 0023 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0024 } /* code 0024 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0025 } /* code 0025 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0026 } /* code 0026 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0027 } /* code 0027 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0028 } /* code 0028 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0029 } /* code 0029 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_002A } /* code 002A */
  ,{   8,   8,  1, acGUI_FontCourierNew16_002B } /* code 002B */
  ,{   8,   8,  1, acGUI_FontCourierNew16_002C } /* code 002C */
  ,{   8,   8,  1, acGUI_FontCourierNew16_002D } /* code 002D */
  ,{   8,   8,  1, acGUI_FontCourierNew16_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_FontCourierNew16_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_003A } /* code 003A */
  ,{   8,   8,  1, acGUI_FontCourierNew16_003B } /* code 003B */
  ,{   8,   8,  1, acGUI_FontCourierNew16_003C } /* code 003C */
  ,{   8,   8,  1, acGUI_FontCourierNew16_003D } /* code 003D */
  ,{   8,   8,  1, acGUI_FontCourierNew16_003E } /* code 003E */
  ,{   8,   8,  1, acGUI_FontCourierNew16_003F } /* code 003F */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0040 } /* code 0040 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0044 } /* code 0044 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0045 } /* code 0045 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0047 } /* code 0047 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0048 } /* code 0048 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_004A } /* code 004A */
  ,{   8,   8,  1, acGUI_FontCourierNew16_004B } /* code 004B */
  ,{   8,   8,  1, acGUI_FontCourierNew16_004C } /* code 004C */
  ,{   8,   8,  1, acGUI_FontCourierNew16_004D } /* code 004D */
  ,{   8,   8,  1, acGUI_FontCourierNew16_004E } /* code 004E */
  ,{   8,   8,  1, acGUI_FontCourierNew16_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0051 } /* code 0051 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0052 } /* code 0052 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0055 } /* code 0055 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0056 } /* code 0056 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0057 } /* code 0057 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0059 } /* code 0059 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_005A } /* code 005A */
  ,{   8,   8,  1, acGUI_FontCourierNew16_005B } /* code 005B */
  ,{   8,   8,  1, acGUI_FontCourierNew16_005C } /* code 005C */
  ,{   8,   8,  1, acGUI_FontCourierNew16_005D } /* code 005D */
  ,{   8,   8,  1, acGUI_FontCourierNew16_005E } /* code 005E */
  ,{   8,   8,  1, acGUI_FontCourierNew16_005F } /* code 005F */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0060 } /* code 0060 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0063 } /* code 0063 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0064 } /* code 0064 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0065 } /* code 0065 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0066 } /* code 0066 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0068 } /* code 0068 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0069 } /* code 0069 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_006A } /* code 006A */
  ,{   8,   8,  1, acGUI_FontCourierNew16_006B } /* code 006B */
  ,{   8,   8,  1, acGUI_FontCourierNew16_006C } /* code 006C */
  ,{   8,   8,  1, acGUI_FontCourierNew16_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_FontCourierNew16_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_FontCourierNew16_006F } /* code 006F */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0071 } /* code 0071 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0072 } /* code 0072 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0073 } /* code 0073 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0075 } /* code 0075 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0076 } /* code 0076 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0077 } /* code 0077 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0078 } /* code 0078 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_0079 } /* code 0079 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_007A } /* code 007A */
  ,{   8,   8,  1, acGUI_FontCourierNew16_007B } /* code 007B */
  ,{   8,   8,  1, acGUI_FontCourierNew16_007C } /* code 007C */
  ,{   8,   8,  1, acGUI_FontCourierNew16_007D } /* code 007D */
  ,{   8,   8,  1, acGUI_FontCourierNew16_007E } /* code 007E */
  ,{   8,   8,  1, acGUI_FontCourierNew16_007F } /* code 007F */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00A0 } /* code 00A0 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00A1 } /* code 00A1 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00A2 } /* code 00A2 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00A3 } /* code 00A3 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00A4 } /* code 00A4 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00A5 } /* code 00A5 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00A6 } /* code 00A6 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00A7 } /* code 00A7 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00A8 } /* code 00A8 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00A9 } /* code 00A9 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00AA } /* code 00AA */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00AB } /* code 00AB */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00AC } /* code 00AC */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00AD } /* code 00AD */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00AE } /* code 00AE */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00AF } /* code 00AF */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00B0 } /* code 00B0 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00B1 } /* code 00B1 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00B2 } /* code 00B2 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00B3 } /* code 00B3 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00B4 } /* code 00B4 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00B5 } /* code 00B5 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00B6 } /* code 00B6 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00B7 } /* code 00B7 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00B8 } /* code 00B8 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00B9 } /* code 00B9 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00BA } /* code 00BA */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00BB } /* code 00BB */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00BC } /* code 00BC */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00BD } /* code 00BD */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00BE } /* code 00BE */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00BF } /* code 00BF */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00C0 } /* code 00C0 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00C1 } /* code 00C1 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00C2 } /* code 00C2 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00C3 } /* code 00C3 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00C4 } /* code 00C4 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00C5 } /* code 00C5 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00C6 } /* code 00C6 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00C7 } /* code 00C7 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00C8 } /* code 00C8 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00C9 } /* code 00C9 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00CA } /* code 00CA */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00CB } /* code 00CB */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00CC } /* code 00CC */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00CD } /* code 00CD */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00CE } /* code 00CE */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00CF } /* code 00CF */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00D0 } /* code 00D0 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00D1 } /* code 00D1 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00D2 } /* code 00D2 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00D3 } /* code 00D3 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00D4 } /* code 00D4 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00D5 } /* code 00D5 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00D6 } /* code 00D6 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00D7 } /* code 00D7 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00D8 } /* code 00D8 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00D9 } /* code 00D9 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00DA } /* code 00DA */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00DB } /* code 00DB */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00DC } /* code 00DC */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00DD } /* code 00DD */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00DE } /* code 00DE */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00DF } /* code 00DF */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00E0 } /* code 00E0 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00E1 } /* code 00E1 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00E2 } /* code 00E2 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00E3 } /* code 00E3 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00E4 } /* code 00E4 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00E5 } /* code 00E5 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00E6 } /* code 00E6 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00E7 } /* code 00E7 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00E8 } /* code 00E8 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00E9 } /* code 00E9 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00EA } /* code 00EA */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00EB } /* code 00EB */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00EC } /* code 00EC */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00ED } /* code 00ED */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00EE } /* code 00EE */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00EF } /* code 00EF */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00F0 } /* code 00F0 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00F1 } /* code 00F1 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00F2 } /* code 00F2 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00F3 } /* code 00F3 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00F4 } /* code 00F4 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00F5 } /* code 00F5 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00F6 } /* code 00F6 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00F7 } /* code 00F7 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00F8 } /* code 00F8 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00F9 } /* code 00F9 */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00FA } /* code 00FA */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00FB } /* code 00FB */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00FC } /* code 00FC */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00FD } /* code 00FD */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00FE } /* code 00FE */
  ,{   8,   8,  1, acGUI_FontCourierNew16_00FF } /* code 00FF */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCourierNew16_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontCourierNew16_CharInfo[ 96] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontCourierNew16_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontCourierNew16_CharInfo[  0] /* address of first character */
  ,&GUI_FontCourierNew16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCourierNew16 = {
	16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCourierNew16_Prop1}
  ,12 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

